import type { TrackerConfig } from '../types';
import type { TrackerClient, TrackerIssueContext, TrackerIssueParams, TrackerIssueResult } from './types';
import { sanitizeSentryTitle, sanitizeSentryData } from '../prompts/sanitizers';
import { GitHubTrackerClient } from './github-tracker';
import { LinearTrackerClient } from './linear-tracker';
import { JiraTrackerClient } from './jira-tracker';

export type { TrackerClient, TrackerIssueParams, TrackerIssueResult, TrackerIssueContext } from './types';

export function createTrackerClient(config: TrackerConfig, repo: string): TrackerClient {
  switch (config.type) {
    case 'github':
      return new GitHubTrackerClient(config, repo);
    case 'linear':
      return new LinearTrackerClient(config);
    case 'jira':
      return new JiraTrackerClient(config);
    default:
      throw new Error(`Unsupported tracker type: ${(config as any).type}`);
  }
}

export function buildIssueBody(context: TrackerIssueContext): string {
  const sanitizedTitle = sanitizeSentryTitle(context.sentryTitle);
  const sanitizedRootCause = sanitizeSentryData(context.triageOutput.root_cause, 2000);
  const sanitizedStackTrace = sanitizeSentryData(context.triageOutput.stack_trace_summary, 2000);
  const sanitizedFix = sanitizeSentryData(context.triageOutput.suggested_fix, 1000);

  const sections = [
    `## DonMerge Sentry Triage`,
    ``,
    `### Sentry Issue`,
    `[${sanitizedTitle}](${context.sentryIssueUrl})`,
    ``,
    `### Root Cause`,
    sanitizedRootCause,
    ``,
    `### Stack Trace Summary`,
    sanitizedStackTrace,
    ``,
    `### Suggested Fix`,
    sanitizedFix,
    ``,
    `### Affected Files`,
    ...context.triageOutput.affected_files.map(f => `- ${sanitizeSentryData(f, 200)}`),
  ];

  if (context.fixPrUrl) {
    sections.push('', `### Fix PR`, context.fixPrUrl);
  }

  sections.push('', '---', '*Auto-generated by [DonMerge](https://donmerge.dev) Sentry Triage*');

  return sections.join('\n');
}

/**
 * Run the tracker issue creation pipeline.
 * Returns the issue URL on success, null on failure/skip.
 * Never throws — all errors are caught and logged.
 */
export async function runCreateIssue(context: TrackerIssueContext): Promise<string | null> {
  try {
    const client = createTrackerClient(context.tracker, context.repo);

    const title = `[Sentry] ${sanitizeSentryTitle(context.sentryTitle).slice(0, 80)}`;
    const body = buildIssueBody(context);
    const labels = context.tracker.labels ?? [];

    const issue = await client.createIssue({ title, body, labels });

    // If a PR was also created, link it via comment (best-effort)
    if (context.fixPrUrl) {
      try {
        await client.addComment(issue.id, `Fix PR: ${context.fixPrUrl}`);
      } catch (error) {
        const msg = error instanceof Error ? error.message : 'unknown';
        console.error('Tracker addComment failed (issue still created)', {
          tracker: context.tracker.type,
          issueKey: issue.key,
          error: msg,
        });
      }
    }

    console.log('Tracker issue created successfully', {
      tracker: context.tracker.type,
      issueKey: issue.key,
      issueUrl: issue.url,
    });

    return issue.url;
  } catch (error) {
    const msg = error instanceof Error ? error.message : 'unknown';
    console.error('Tracker issue creation failed', {
      tracker: context.tracker.type,
      error: msg,
    });
    return null;
  }
}
